# Generated by Django 4.1.2 on 2022-10-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='text',
            field=models.FileField(upload_to=''),
        ),
    ]
