export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAIL = 'FILE_UPLOAD_FAIL'
export const FILE_UPLOAD_RESET = 'FILE_UPLOAD_RESET'

export const FILE_GET_REQUEST = 'FILE_GET_REQUEST'
export const FILE_GET_SUCCESS = 'FILE_GET_SUCCESS'
export const FILE_GET_FAIL = 'FILE_GET_FAIL'